sudo: required
dist: precise
language: cpp  
compiler: g++
addons:
    apt:
        sources: 
          - 'ubuntu-toolchain-r-test'
        packages: 
          - 'g++-5'
env: COMPILER=g++-5

before_install:
   - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
   - sudo apt-get update -qq
   - sudo apt-get install cmake-data

install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
   - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"
   
script:
    - mkdir _builds
    - cd _builds
    - cmake -DBUILD_TEST=TRUE -DCMAKE_CXX_COMPILER=$COMPILER ..
    - make
    - test_bin
    