language: cpp  
compiler: clang
addons:
    apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['cmake','clang-3.6', 'g++-4.9']

before_install:
   - sudo add-apt-repository -y ppa:h-rayflood/llvm
   - sudo apt-get update -qq

install:
   - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}""

script:
    - mkdir _builds
    - cd _builds
    - cmake .. -DBUILD_TEST=TRUE
    - make
    - test_bin
    