language: cpp  
compiler: clang
addons:
    apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['cmake','clang-3.6', 'g++-4.9']

install:
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake .
   - sudo make
   - sudo mv libgtest* /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}""

script:
    - mkdir _builds
    - cd _builds
    - cmake .. -DBUILD_TEST=TRUE
    - make
    - test_bin
    